StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6070A09F7C9276AA}" {
   Id "Abrams-EditableEntity_M1A1_Name"
   Target_en_us "M1A1 Abrams"
   Comment "Enity placed via the content Browser"
   MaxLength 0
   Modified 1617994757
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{6070A09F284710CE}" {
   Id "Abrams-EditableEntity_M1A2_Name"
   Target_en_us "M1A2 Abrams"
   Modified 1617994727
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{6070A09F2DAED935}" {
   Id "Abrams-EditableEntity_M1A2_TUSK_Name"
   Target_en_us "M1A2 Abrams TUSK"
   Modified 1660426581
   Author "Ethan Benzel"
   LastChanged "thoma"
  }
  CustomStringTableItem "{6070A09F32160A41}" {
   Id "Abrams-EditableEntity_M1A2_TUSKII_Name"
   Target_en_us "M1A2 Abrams TUSK II"
   Modified 1660426575
   Author "Ethan Benzel"
   LastChanged "thoma"
  }
 }
}